import type {
  Citation,
  CitedText,
  EligibilityChecklist,
  EligibilityItem,
  MoneyAmount,
  RedFlag,
  RedFlagIndicator,
  TenderDocument,
} from '@/api/types'
import { RED_FLAG_INDICATORS } from '@/api/types'

// Times are relative to page load, so deadlines and "updated X min ago" always look current.
const NOW = Date.now()
const MINUTE = 60 * 1000
export const minutesAgo = (n: number) => new Date(NOW - n * MINUTE).toISOString()
export const hoursAgo = (n: number) => minutesAgo(n * 60)
export const daysAgo = (n: number) => minutesAgo(n * 24 * 60)
export const daysFromNow = (n: number) => daysAgo(-n)

/** When the backend last pulled MTender in the mock world. */
export const LAST_SYNC_AT = minutesAgo(12)

export const mdl = (amount: number): MoneyAmount => ({ amount, currency: 'MDL' })

/** Mock documents open a local placeholder page instead of a real PDF. */
const mockUrl = (title: string) => `/mock-document.html?title=${encodeURIComponent(title)}`

export function doc(
  document_id: string,
  title: string,
  options: Partial<Omit<TenderDocument, 'document_id' | 'title' | 'url'>> = {},
): TenderDocument {
  return {
    document_id,
    title,
    url: mockUrl(title),
    source: 'mtender',
    participant_id: null,
    language: 'ro',
    page_count: null,
    published_at: null,
    analysis_status: 'analyzed',
    analyzed_at: null,
    ...options,
  }
}

export function cite(document: TenderDocument, page: number | null): Citation {
  return {
    document_id: document.document_id,
    document_title: document.title,
    url: document.url,
    page,
  }
}

/** Evidence taken from MTender records rather than from a document. */
export function record(document_id: string, title: string): Citation {
  return { document_id, document_title: title, url: mockUrl(title), page: null }
}

export const cited = (text: string, ...citations: Citation[]): CitedText => ({ text, citations })

/** All six indicators; the ones given evidence are triggered. */
export function redFlags(evidence: Partial<Record<RedFlagIndicator, CitedText[]>> = {}): RedFlag[] {
  return RED_FLAG_INDICATORS.map((indicator) => ({
    indicator,
    triggered: indicator in evidence,
    evidence: evidence[indicator] ?? [],
  }))
}

export function checklist(
  tender_id: string,
  items: EligibilityItem[],
  profile_id: number | null = 1,
): EligibilityChecklist {
  return {
    tender_id,
    profile_id,
    items,
    met_count: items.filter((item) => item.met === true).length,
    total_count: items.length,
    disclaimer:
      'This checklist is generated by an AI assistant and is not legal advice. ' +
      'Always verify requirements with the original tender documents.',
  }
}

export const WIN_CHANCE_DISCLAIMER =
  'Win-chance is estimated from historical patterns only. ' +
  'Active competitor bids are not public before bid opening.'
