"""
Pydantic schemas — source of truth for all API I/O.
Shared between the API layer and frontend mock data.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Shared primitives
# ---------------------------------------------------------------------------


class Language(str, Enum):
    ro = "ro"
    ru = "ru"
    en = "en"


class MoneyAmount(BaseModel):
    amount: float
    currency: str = "MDL"


# ---------------------------------------------------------------------------
# Company profile
# ---------------------------------------------------------------------------


class ProfileCreate(BaseModel):
    idno: str | None = Field(None, description="Moldovan tax ID (IDNO), 13 digits")
    name: str
    description: str = Field(
        ..., description="Free-text description used for semantic matching"
    )
    cpv_codes: list[str] = Field(default_factory=list)
    regions: list[str] = Field(default_factory=list)
    budget_min: float | None = None
    budget_max: float | None = None


class ProfileOut(ProfileCreate):
    id: int
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------


class SearchResult(BaseModel):
    tender_id: str
    title: str
    buyer_name: str
    estimated_value: MoneyAmount | None
    deadline: datetime | None
    fit_score: float = Field(..., ge=0, le=1)
    match_snippet: str = Field(
        ..., description="Why this tender matched (semantic highlight)"
    )
    red_flag_count: int = 0


class SearchResponse(BaseModel):
    query: str
    profile_id: int | None
    results: list[SearchResult]
    total: int


# ---------------------------------------------------------------------------
# Red flags / integrity indicators
# ---------------------------------------------------------------------------


class RedFlag(BaseModel):
    indicator: str
    triggered: bool
    evidence: list[str] = Field(
        default_factory=list,
        description="Data points or page citations supporting the indicator",
    )


# ---------------------------------------------------------------------------
# Eligibility checker
# ---------------------------------------------------------------------------


class EligibilityItem(BaseModel):
    requirement: str
    requirement_type: str  # "financial" | "technical" | "legal" | "administrative"
    threshold: str | None
    source_page: int | None
    met: bool | None = None  # None = not evaluated against a profile
    notes: str | None = None


class EligibilityChecklist(BaseModel):
    tender_id: str
    profile_id: int | None
    items: list[EligibilityItem]
    met_count: int
    total_count: int
    disclaimer: str = (
        "This checklist is generated by an AI assistant and is not legal advice. "
        "Always verify requirements with the original tender documents."
    )


# ---------------------------------------------------------------------------
# Win-chance estimate
# ---------------------------------------------------------------------------


class WinChanceEstimate(BaseModel):
    tender_id: str
    estimated_probability: float | None = Field(None, ge=0, le=1)
    typical_bidder_count: float | None
    typical_winning_ratio: float | None = Field(
        None, description="Typical winning price / estimated value"
    )
    buyer_concentration: float | None = Field(
        None, description="Fraction of contracts awarded to a single repeat winner"
    )
    disclaimer: str = (
        "Win-chance is estimated from historical patterns only. "
        "Active competitor bids are not public before bid opening."
    )


# ---------------------------------------------------------------------------
# Full tender analysis  (GET /tenders/{id}/analysis)
# ---------------------------------------------------------------------------


class TenderAnalysis(BaseModel):
    tender_id: str
    fit_score: float | None
    red_flags: list[RedFlag]
    eligibility: EligibilityChecklist | None
    win_chance: WinChanceEstimate | None


# ---------------------------------------------------------------------------
# Buyer profile  (GET /buyers/{id}/profile)
# ---------------------------------------------------------------------------


class BuyerProfile(BaseModel):
    buyer_id: str
    name: str
    total_tenders: int
    single_bidder_rate: float | None = Field(None, ge=0, le=1)
    repeat_winner_concentration: float | None = Field(None, ge=0, le=1)
    top_winners: list[dict[str, Any]] = Field(default_factory=list)
