/**
 * Region suggestions, written the way tenders name them ("mun. Chișinău", "r. Ungheni"),
 * so the names the user picks match the tenders' regions exactly.
 */
export const REGIONS = [
  'mun. Chișinău',
  'mun. Bălți',
  'mun. Bender',
  'mun. Comrat',
  'UTA Găgăuzia',
  ...[
    'Anenii Noi',
    'Basarabeasca',
    'Briceni',
    'Cahul',
    'Cantemir',
    'Călărași',
    'Căușeni',
    'Cimișlia',
    'Criuleni',
    'Dondușeni',
    'Drochia',
    'Dubăsari',
    'Edineț',
    'Fălești',
    'Florești',
    'Glodeni',
    'Hîncești',
    'Ialoveni',
    'Leova',
    'Nisporeni',
    'Ocnița',
    'Orhei',
    'Rezina',
    'Rîșcani',
    'Sîngerei',
    'Soroca',
    'Strășeni',
    'Șoldănești',
    'Ștefan Vodă',
    'Taraclia',
    'Telenești',
    'Ungheni',
  ].map((district) => `r. ${district}`),
] as const
